# �˿ں�
server:
  port: 7900
# ���ݿ��������
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  # ����Դ
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.92.122.203:3306/costmanagement
    username: root
    password: Aa123456!
